name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Images
        run: docker-compose build

      - name: Run Docker Containers
        run: docker-compose up -d

      - name: Wait for services
        run: |
          sleep 30  # Wait for services to start